language: scala
scala:
   - 2.11.7

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

jdk:
  - oraclejdk8

services:
  - mongodb
  - redis-server
  - rabbitmq

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'